# Mobilfunkmasten und Netzabdeckung

Open in Colab: [![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/febse/opt2025-de/blob/main/cell_tower.ipynb)


In den letzten zwei Jahrzehnten hat sich die Mobilfunktechnologie rasant entwickelt und der Bedarf an Mobilfunkdiensten ist stetig gestiegen. Diese Dienste werden durch ein Netz von Mobilfunkmasten bereitgestellt, die in der Regel von Mobilfunkbetreibern betrieben werden.

Die Errichtung von Mobilfunkmasten ist jedoch mit Kosten verbunden, und die Netzbetreiber müssen sicherstellen, dass die Mobilfunkmasten so platziert werden, dass sie eine optimale Netzabdeckung bieten und gleichzeitig die Anzahl der Mobilfunkmasten so klein wie möglich ist.

![Cell Tower Coverage](https://media.rnztools.nz/rnz/image/upload/s--5-nd_aXq--/c_scale,f_auto,q_auto,w_1050/v1651703353/4LTH50J_image_crop_141730)


[Excel Datei](./excel/cell_towers.xlsx)

## Problemstellung

Ein Mobilfunknetzbetreiber plant die Errichtung einer Reihe von Mobilfunkmasten, um die Bewohner einer bestimmten Stadt mit einem Signal zu versorgen. Die Stadt wurde in einem früheren Schritt in eine Reihe von Regionen unterteilt. Der Betreiber muss nun entscheiden in welchen Regionen er Mobilfunkmasten errichten soll, um die größtmögliche Anzahl von Bewohnern zu erreichen. Dabei dürfen die Kosten das verfügbare Budget nicht überschreiten. Die Anzahl der Bewohner in jeder Region ist bekannt und in der folgenden Tabelle aufgeführt:

In [9]:
import pandas as pd

loc_reg_data = [
    ["Standort 0", 1, 1, 0, 0, 0, 1, 0, 0, 0],
    ["Standort 1", 1, 0, 0, 0, 0, 0, 0, 1, 1],
    ["Standort 2", 0, 0, 1, 1, 1, 0, 1, 0, 0],
    ["Standort 3", 0, 0, 1, 0, 0, 1, 1, 0, 0],
    ["Standort 4", 1, 0, 1, 0, 0, 0, 1, 1, 1],
    ["Standort 5", 0, 0, 0, 1, 1, 0, 0, 0, 1]
]

regions = ["Region 1", "Region 2", "Region 3", "Region 4", "Region 5", "Region 6", "Region 7", "Region 8", "Region 9"]

lr = pd.DataFrame(loc_reg_data, columns=["Standort"] + regions)
lr.set_index("Standort", inplace=True)

pop_data = [523, 690, 420, 1010, 1200, 850, 400, 1008, 950]
pop = pd.Series(
    pop_data, 
    name="Einwohner",
    index=regions
)

pop.to_frame()

          Einwohner
Region 1        523
Region 2        690
Region 3        420
Region 4       1010
Region 5       1200
Region 6        850
Region 7        400
Region 8       1008
Region 9        950

Die Reichweiten der Mobilfunkmasten je nach Standort sind ebenfalls bekannt und in der folgenden Tabelle aufgeführt:

In [10]:
lrxl = lr.copy()

lrxl.loc[pop.name] = pop
costs = [4.2, 6.1, 5.2, 5.5, 4.8, 9.2]
lrxl["Kosten"] = [*costs, None]

# lrxl.to_excel("cell_towers.xlsx")
lrxl

,Region 1,Region 2,Region 3,Region 4,Region 5,Region 6,Region 7,Region 8,Region 9,Kosten
Standort,,,,,,,,,,
Standort 0,1,1,0,0,0,1,0,0,0,4.2
Standort 1,1,0,0,0,0,0,0,1,1,6.1
Standort 2,0,0,1,1,1,0,1,0,0,5.2
Standort 3,0,0,1,0,0,1,1,0,0,5.5
Standort 4,1,0,1,0,0,0,1,1,1,4.8
Standort 5,0,0,0,1,1,0,0,0,1,9.2
Einwohner,523,690,420,1010,1200,850,400,1008,950,NaN

## Modellierung

### Entscheidungsvariablen

### Parameter

## Zielfunktion


## Nebenbedingungen


### Budgetbeschränkung

## Umsetzung